name: 'build'

on:
  push:
    # Only used for build stage.
    branches:
    - main
    paths-ignore:
    - '*.md'
    - '*.png'
    # Publish 1.2.3 and 'latest' tags as releases.
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '*.md'
    - '*.png'
    types: [opened, synchronize, reopened] # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request

env:
  # This will suppress any downloads for dependencies and plugins or upload messages that would clutter the console log.
  # Opting for this approach because --no-transfer-progress or -ntp may be suppressing even warning and error messages.
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
  MAVEN_CLI_OPTS: --batch-mode --errors --fail-at-end --show-version -Dstyle.color=always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy.
        fetch-depth: 0

    # Step also needed to avoid issues with sonarscanner and preinstalled Java 11.
    - name: Install Temurin OpenJDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        architecture: x64

    - name: Cache SonarCloud Packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven Packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Maven Package # Using JVM mode.
      run: chmod +x ./mvnw && ./mvnw $MAVEN_CLI_OPTS -DskipTests clean package

    - name: Maven Test and SonarCloud
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any.
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        ./mvnw $MAVEN_CLI_OPTS verify sonar:sonar \
          -Dsonar.projectKey="StevenJDH_covid-tracker" \
          -Dsonar.organization="stevenjdh" \
          -Dsonar.host.url="https://sonarcloud.io" \
          -Dsonar.token=$SONAR_TOKEN

    - name: Upload Artifact
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: repo-src
        path: |
          ${{ github.workspace }}
          !.git/
          !.github/
          !.mvn/
          !*.md
        retention-days: 1

  push_to_registries:
    name: Deploy Containers
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    environment: prod
    if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
    needs: build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: repo-src

    - name: Generate Docker Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        # List of container registry names to use for image tagging.
        # Everything will be automatically set to lowercase.
        images: |
          public.ecr.aws/${{ github.repository }},enable=true
          docker.io/${{ github.repository }},enable=true
          ghcr.io/${{ github.repository }},enable=true
        # Generates Docker tags based on the following events/attributes.
        tags: |
          type=ref,event=branch,enable=false
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Login to AWS Public ECR
      uses: docker/login-action@v3
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      env:
        # Must be us-east-1 for requesting authentication token.
        # Reference: https://docs.aws.amazon.com/AmazonECR/latest/public/getting-started-cli.html#cli-authenticate-registry
        AWS_REGION: us-east-1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build, Tag, and Push Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}